In [2]:
import numpy as np


In [3]:
np.array([[1,2,3],[4,5,6],[7,8,9]])


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
data = np.array([[0.987,0.45,0.123],[12.45,56.1,0.087]])
data

array([[ 0.987,  0.45 ,  0.123],
       [12.45 , 56.1  ,  0.087]])

In [5]:
data.dtype


dtype('float64')

In [6]:
data1 = [6,7.5,8,0,1] 
#A list is converted into an array
#Since data is mixed, it is made uniform, i.e all  is made float
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [8]:
data2 = [[1,2,3,4],[5,6,7,8]]
#A nested list of equal-length lists will be converted into a multidimensional array
arr2 = np.array(data2)
arr2


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
arr2.shape #No. of rows and how many items in each row

(2, 4)

In [10]:
arr2.ndim #It tells the dimensions of the array

2

In [11]:
np.zeros(10) #1D array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.zeros((3,3)) #3X3 dimensional array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.zeros((5,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [14]:
np.ones((3,3)) 

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.empty((4,5)) #Gives us garbage Values

array([[6.23042070e-307, 1.86918699e-306, 1.69121096e-306,
        1.06810404e-306, 7.56587584e-307],
       [7.56593017e-307, 1.24610383e-306, 1.24610723e-306,
        1.37962320e-306, 1.29060871e-306],
       [2.22522597e-306, 1.33511969e-306, 1.78022342e-306,
        1.05700345e-307, 1.11261027e-306],
       [1.29061142e-306, 6.23057349e-307, 1.69121096e-306,
        1.42410974e-306, 2.56761491e-312]])

In [18]:
np.arange(15) #1D array of values form 0 to 14

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
np.arange((3,3,9)) #arange can only have scalar input and not tuples

TypeError: arange: scalar arguments expected instead of a tuple.

In [21]:
np.zeros((3,4,5)) # 3 matrices of 4x5 dimesnsional matrix

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [22]:
np.zeros((3,4,5,6)) # we get (3x4=12) matrices of dimension 5x6

array([[[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
        

In [26]:
sample = np.zeros((3,4,5,6,7))
sample
#We get (3x4x5=60) matrices of dimension 6x7 and so on.

array([[[[[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

         [[0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.],
          [0., 0., 0., ..., 0., 0., 0.]],

        

In [27]:
sample.shape

(3, 4, 5, 6, 7)

In [28]:
sample.ndim

5

In [29]:
np.eye(4) #identity matrix with a scalar input

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [31]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
arr*arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [33]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [34]:
arr+arr

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [35]:
arr*8.9

array([[ 8.9, 17.8, 26.7],
       [35.6, 44.5, 53.4]])

In [36]:
arr**0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])